<center><h1>ASSIGNMET, DAY-3, DATA SCIENCE ESENTIALS</h1></center>
<center><h1>--------------------------------------------------------------------</h1></center>

In [1]:
import numpy as np

<b>Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.</b>

In [2]:
arr = np.arange(2,51,3)

In [3]:
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


<b>Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.</b>

In [4]:
list_1 = []

print("Enter the elements of 1st List: ")
for i in range(1,6):
    e = int(input())
    list_1.append(e)

print("Enter the elements of 2nd List: ")
list_2 = []
for j in range(1,6):
    f = int(input())
    list_2.append(f)
print("1st List = ",list_1)
print("2nd List = ",list_2)
arr1 = np.array(list_1)
print("1st Array = ",arr1)
arr2 = np.array(list_2)
print("2nd Array = ",arr2)
arr3 = np.concatenate((arr1,arr2))
print("Concateneted array = ",arr3)
s_arr1 = print("Sorted 1st Array = ",np.sort(arr1))
s_arr2 = print("sorted 2nd Array = ",np.sort(arr2))
s_arr3 = print("sorted concatenated array = ",np.sort(arr3))

Enter the elements of 1st List: 
4
7
8
5
1
Enter the elements of 2nd List: 
2
4
7
5
6
1st List =  [4, 7, 8, 5, 1]
2nd List =  [2, 4, 7, 5, 6]
1st Array =  [4 7 8 5 1]
2nd Array =  [2 4 7 5 6]
Concateneted array =  [4 7 8 5 1 2 4 7 5 6]
Sorted 1st Array =  [1 4 5 7 8]
sorted 2nd Array =  [2 4 5 6 7]
sorted concatenated array =  [1 2 4 4 5 5 6 7 7 8]


<b>Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.</b>

In [5]:
print("1D Array: ")
arr_1d = np.arange(5)
print(arr_1d)
print("Dimension = ",arr_1d.ndim) # ndim is the code snipppet used to find the dimension of a ndarray array
print("Size = ",arr_1d.size) # size is the code snippet used to find the size of ndarray
print()

print("2D Array: ")
arr_2d = np.arange(16).reshape((4, 4))
print(arr_2d)
print("Dimension = ",arr_2d.ndim) # ndim is the code snipppet used to find the dimension of a ndarray array
print("Size = ",arr_2d.size) # size is the code snippet used to find the size of ndarray
print()

print("3D Array: ")
arr_3d = np.arange(24).reshape((2, 3, 4))
print(arr_3d)
print("Dimension = ",arr_3d.ndim) # ndim is the code snipppet used to find the dimension of a ndarray array
print("Size = ",arr_3d.size) # size is the code snippet used to find the size of ndarray
print()

1D Array: 
[0 1 2 3 4]
Dimension =  1
Size =  5

2D Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimension =  2
Size =  16

3D Array: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Dimension =  3
Size =  24



<b>Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet</b>

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("1D Array :")
print(arr)
print()

# Converting 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print("2D Array : ")
print(arr_2d)

1D Array :
[0 1 2 3 4 5 6 7 8 9]

2D Array : 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
# Converting 1D array to a 2D numpy array of incompatible shape will cause error
arr_2d = np.reshape(arr, (2, 3))

ValueError: cannot reshape array of size 10 into shape (2,3)

<b>Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()</b>

In [8]:
arr1 = np.arange(16).reshape(4,4)
arr2 = np.arange(16).reshape(4,4)
V_Stack = np.vstack((arr1,arr2))
H_Stack = np.hstack((arr1,arr2))
print("Vertically Stacked : ")
print(V_Stack)
print()
print("Horizontally Stacked : ")
print(H_Stack)

Vertically Stacked : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontally Stacked : 
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


<b>Questions 6:
How to get unique items and counts of unique items?</b>

We can find the unique elements and their count in numpy by using 'numpy.unique()' function and passing 1st argument as the given array and setting the retutn_counts value to True. Below is example of this

In [9]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(number_list, return_counts=True)
print(unique,counts)

[1 2 3 4] [3 1 1 2]
